# Generated by Django 3.0.3 on 2020-04-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePicture',
            new_name='image',
        ),
    ]
